apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: matrix-signingkey
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  signing.key: {{ index .Values "matrix-synapse" "signingkey" "key" | b64enc | quote }}
