apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  name: synapse
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: synapse
  ignoreDifferences:
    - group: core
      jsonPointers:
        - /spec/volumeName
      kind: PersistentVolumeClaim
  project: default
  source:
    helm:
      releaseName: synapse
      valueFiles:
        - values.yaml
        - secrets.values.yaml
    path: matrix/synapse
    repoURL: https://github.com/AlexanderBabel/kubernetes-config-summit-2022.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
